export const WEATHER_REQUEST = 'WEATHER_REQUEST';
export const WEATHER_SUCCESS = 'WEATHER_SUCCESS';
export const WEATHER_FAILURE = 'WEATHER_FAILURE';
export const CLEAR_WEATHER = 'CLEAR_WEATHER';


export const FORECAST_REQUEST = 'FORECAST_REQUEST';
export const FORECAST_SUCCESS = 'FORECAST_SUCCESS';
export const FORECAST_FAILURE = 'FORECAST_FAILURE';
export const CLEAR_FORECAST = 'CLEAR_WEATHER';

